### PR TITLE
Add more tests for RabbitMQTransport.Connect

### PR DESCRIPTION
**Pull request by mihaitodor**
As discussed [here](https://github.com/upfluence/sensu-go/pull/3#issuecomment-267404357), I have added some interfaces to the `RabbitMQTransport` code in order to make it more testable and I have added a few tests for `RabbitMQTransport.Connect`.

### CODE REVIEW

**Comment by AlexisMontagne** [comment]
So many PRs! 😄 , im confused.

I gave you feedbacks on the #5, this is the only issues i've seen.

**Comment by mihaitodor** [comment]
Yeah, quite a few :) I'll address those comments in this PR, since the other 2 depend on this one...

**Comment by mihaitodor** [comment]
@AlexisMontagne I have addressed https://github.com/upfluence/sensu-go/pull/5#discussion_r96460339 in this PR. Once merged, I'll rebase the other 2, because they should go on top of this one.

**Comment by AlexisMontagne** [comment]
LGTM, i will merge this one, ping me when you rebased the two others.

**Pull request merged**
